<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vps_uav_benchmarking</name>
  <version>0.0.1</version>
  <description>Benchmarking and analysis tools for UAV Visual Positioning Systems (VPS)</description>
  <maintainer email="uvats_be23@thapar.edu">Arnav</maintainer>
  <license>Confidential</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <exec_depend>rclpy</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rosbag2_py</exec_depend>
  <exec_depend>orbbec_camera</exec_depend>
  <exec_depend>ov_msckf</exec_depend>
  <exec_depend>isaac_ros_visual_slam</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
